
web:
  build: .
  working_dir: /data
  command: python exercicio-2.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5000:5000"

db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: dsoares04
  ports:
    - "3309:3309"
